apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo
spec:
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
      - name: devops-demo
        image: kyoseok/devops_sample:docker_tag
        command: ["/bin/sh"]
        args: ["-c","sh /usr/local/tomcat/bin/startup.sh;while true; do echo hello; sleep 10;done"]
        ports:
            - name: http
              containerPort: 8080
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: devops-demo-app-service
  labels:
    app: devops-demo
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31884
    protocol: TCP
    name: http
  selector:
    app: devops-demo
